-- SQL for Technetics: Hogwarts Edition
-- Run these in your Supabase SQL Editor

-- Table for Github/Deployment Submissions
CREATE TABLE IF NOT EXISTS public.github_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name TEXT NOT NULL,
    deploy_link TEXT NOT NULL,
    github_end_time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table for Dark Mark Bounty attempts
CREATE TABLE IF NOT EXISTS public.bounty_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name TEXT NOT NULL,
    code TEXT NOT NULL,
    status TEXT NOT NULL, -- 'success', 'failed', 'active'
    points_earned INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Disable RLS for easy access (as requested: non-RLS)
ALTER TABLE public.github_submissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.bounty_attempts DISABLE ROW LEVEL SECURITY;

-- Grant access to anon role
GRANT ALL ON public.github_submissions TO anon;
GRANT ALL ON public.bounty_attempts TO anon;
GRANT ALL ON public.github_submissions TO authenticated;
GRANT ALL ON public.bounty_attempts TO authenticated;
GRANT ALL ON public.github_submissions TO service_role;
GRANT ALL ON public.bounty_attempts TO service_role;
